'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven

    Partial Public Class CSSToolbar

        '''<summary>
        '''TMPnlNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlNew As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNew As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TMPnlRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlRefresh As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnRefresh As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TMPnlSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlSave As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnSave As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkIsAllowAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowAdd As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsAllowEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowEdit As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TMPnlDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlDelete As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkIsAllowDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowDelete As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TMpnlPropose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMpnlPropose As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnPropose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnPropose As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TMPnlApprove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlApprove As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnApprove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnApprove As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkIsAllowApprove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowApprove As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TMPnlVoid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlVoid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnVoid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnVoid As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkIsAllowVoid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowVoid As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TMPnlPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlPrint As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnPrint As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkIsAllowPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAllowPrint As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TMpnlAttach control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMpnlAttach As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnAttach control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnAttach As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TMPnlPrevious control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlPrevious As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnPrevious control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnPrevious As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TMPnlNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TMPnlNext As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNext As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblMenuID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMenuID As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
