'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven

    Partial Public Class ProjectBanner

        '''<summary>
        '''lblProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomerID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomerID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkOrderNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkOrderNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkOrderDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkOrderDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblJobDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblJobDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriod As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
