'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven

    Partial Public Class RadMenu

        '''<summary>
        '''ScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''lblApplicationID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblApplicationID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblApplicationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblApplicationName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUserFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserFullName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProfileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lblCompanyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''repApplication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repApplication As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Menu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Menu As Global.CommonLibs.Menu
    End Class
End Namespace
