'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure

    Partial Public Class CustomerInspectionInformation

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.Raven.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.Raven.CSSToolbar

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtCustomerID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCustomerCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearchCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchCustomer As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''rfvCustomerCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCustomerCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtProductID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProductID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProductCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProductCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearchProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchProduct As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProductName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rtsInspectionInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtsInspectionInformation As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''rmpInspectionInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rmpInspectionInformation As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''pvInspectionByWorkRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvInspectionByWorkRequest As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''ddlInformationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlInformationType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlHistoryCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHistoryCaption As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlDueCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDueCaption As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHistory As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtLast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLast As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlDue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDue As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtDueIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDueIn As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdCustomerInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCustomerInspection As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pvInformationDashboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvInformationDashboard As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''ddlInformationTypeSOI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlInformationTypeSOI As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPeriod As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPeriod As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPeriod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlCustomPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCustomPeriod As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''calStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDate As Global.Raven.Web.Calendar

        '''<summary>
        '''calEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDate As Global.Raven.Web.Calendar

        '''<summary>
        '''txtWorkOrderNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkOrderNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProjectCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlInspectionTotalSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInspectionTotalSummary As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTotalWorkOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalWorkOrder As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemIspected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemIspected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnAccepted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnAccepted As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemAccepted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemAccepted As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemAcceptedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemAcceptedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnRepair control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnRepair As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemNeedRepair control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemNeedRepair As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemNeedRepairPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemNeedRepairPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnRejected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnRejected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemRejected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemRejected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemRejectedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemRejectedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlDueToExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDueToExpired As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtItemDueToExpiredInspectionInDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemDueToExpiredInspectionInDay As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdItemDueToExpiredInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdItemDueToExpiredInspection As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pvInspectionByItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvInspectionByItem As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSerialNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdInspectionBySerialIDNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdInspectionBySerialIDNo As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.Raven.Web.copyRight
    End Class
End Namespace
