'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure

    Partial Public Class CustomerInspectionInformationDetail

        '''<summary>
        '''frmkunjPoli control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmkunjPoli As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''lblWRNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWRNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtsDetailInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtsDetailInformation As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''rmpDetailInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rmpDetailInformation As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''pvProjectFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvProjectFile As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdProjectFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProjectFile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pvDailyReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvDailyReport As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdDailyReportHd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDailyReportHd As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblDailyReportHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDailyReportHdID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdDailyReportDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDailyReportDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pvResourceFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvResourceFile As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdResourceFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdResourceFile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pvSOIByWorkRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pvSOIByWorkRequest As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''lblTotalItemIspected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemIspected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnAccepted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnAccepted As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemAccepted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemAccepted As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemAcceptedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemAcceptedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnRepair control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnRepair As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemNeedRepair control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemNeedRepair As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemNeedRepairPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemNeedRepairPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnRejected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnRejected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTotalItemRejected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemRejected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalItemRejectedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalItemRejectedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LinkButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblItemRejected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemRejected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblItemRejectedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemRejectedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LinkButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButton2 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblItemClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemClass2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblItemClass2Pct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemClass2Pct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdSummaryOfInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdSummaryOfInspection As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
