'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure

    Partial Public Class InspectionSpec

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.Raven.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.Raven.CSSToolbar

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtInspectionSpecificationID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInspectionSpecificationID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtInspectionSpecificationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInspectionSpecificationCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvInspectionSpecificationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvInspectionSpecificationCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtInspectionSpecificationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInspectionSpecificationName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtConnection As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtGrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGrade As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRange As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNominalWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNominalWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinODPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinODPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinShoulderPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinShoulderPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxIDPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxIDPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinBevelDiaPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinBevelDiaPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinWallPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinWallPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinSealPremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinSealPremium As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinODClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinODClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinShoulderClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinShoulderClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxIDClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxIDClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBevelDiaClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBevelDiaClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinWallClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinWallClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinSealClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinSealClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinTongSpacePinClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinTongSpacePinClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinTongSpaceBoxClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinTongSpaceBoxClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxLengthPinClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxLengthPinClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxPinNeckClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxPinNeckClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinQCDepthClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinQCDepthClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxQCClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxQCClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxCBoreClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxCBoreClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaxBevelDiaClass2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxBevelDiaClass2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdInspectionSpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdInspectionSpec As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.Raven.Web.copyRight
    End Class
End Namespace
