'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web

    Partial Public Class Main

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.Raven.RadMenu

        '''<summary>
        '''chkIsCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsCustomer As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlAdministratorScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAdministratorScreen As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtWorkRequestListFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkRequestListFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlWorkRequestListFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlWorkRequestListFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtWorkRequestListDisplayFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkRequestListDisplayFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnWorkRequestListFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnWorkRequestListFilter As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdWorkRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdWorkRequest As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlInspectorScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInspectorScreen As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlMySite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMySite As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProjectCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearchProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchProject As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtProjectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdReportTypeByProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdReportTypeByProject As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''ProjectBanner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProjectBanner As Global.Raven.ProjectBanner

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.Raven.CSSToolbar

        '''<summary>
        '''lblReportTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTypeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportTypeName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTypeName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportTypePanelID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTypePanelID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlCheckListCompletionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCheckListCompletionReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''CCR_txtCCRID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtCCRID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_ddlTypeOfReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_ddlTypeOfReport As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CCR_txtPreparedByName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtPreparedByName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_calPreparedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_calPreparedDate As Global.Raven.Web.Calendar

        '''<summary>
        '''CCR_txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CCR_grdCheckListOfCompletionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCR_grdCheckListOfCompletionReport As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlServiceAcceptance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlServiceAcceptance As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlSummaryOfInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSummaryOfInspection As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SOI_pnlApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_pnlApproved As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SOI_lblApprovalBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_lblApprovalBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SOI_lblApprovalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_lblApprovalDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SOI_rbtnlInputMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_rbtnlInputMethod As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''SOI_pnlEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_pnlEntry As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SOI_txtSummaryOfInspectionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtSummaryOfInspectionID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtDescOfEquip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtDescOfEquip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtSerialNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtManufacture control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtManufacture As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtSWLWWLMGW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtSWLWWLMGW As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtDimensional control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtDimensional As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtDefectFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtDefectFound As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtResult As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_calExamDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_calExamDate As Global.Raven.Web.Calendar

        '''<summary>
        '''SOI_calExpiredDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_calExpiredDate As Global.Raven.Web.Calendar

        '''<summary>
        '''SOI_txtReportNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtReportNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_chkIsV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_chkIsV As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SOI_chkIsN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_chkIsN As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SOI_chkIsT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_chkIsT As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SOI_txtInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtInterval As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFileUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFileUrl As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''SOI_pnlUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_pnlUpload As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SOI_File control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_File As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''SOI_FileDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_FileDetail As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''SOI_txtSheetName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_txtSheetName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SOI_grdSummaryOfInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SOI_grdSummaryOfInspection As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlTimeSheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTimeSheet As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''TS_ddlMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TS_ddlMonth As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TS_ddlYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TS_ddlYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TS_chkIsAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TS_chkIsAll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''repDateInMonthHd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repDateInMonthHd As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lvwTimeSheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lvwTimeSheet As Global.System.Web.UI.WebControls.ListView

        '''<summary>
        '''pnlDailyProgressReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDailyProgressReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''DPR_txtDailyReportHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtDailyReportHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_btnSearchDailyReportHd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_btnSearchDailyReportHd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DPR_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''DPR_txtDailyReportDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtDailyReportDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_ddlWeatherCondition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_ddlWeatherCondition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DPR_txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_txtQtyCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtQtyCurrent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_txtQtyPrevious control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtQtyPrevious As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_txtQtyCumulative control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_txtQtyCumulative As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DPR_grdDailyReportDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DPR_grdDailyReportDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlDailyInspectionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDailyInspectionReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''DIR_txtDailyReportHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtDailyReportHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_btnSearchDailyReportHd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_btnSearchDailyReportHd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DIR_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''DIR_txtDailyReportDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtDailyReportDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_ddlWeatherCondition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_ddlWeatherCondition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DIR_txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_txtQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtQty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_txtResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_txtResult As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DIR_grdDailyReportDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DIR_grdDailyReportDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlServiceReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlServiceReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SR_ddlServiceReportFor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_ddlServiceReportFor As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SR_txtServiceReportID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtServiceReportID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_calServiceReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_calServiceReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''SR_txtTypeOfInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtTypeOfInspection As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_pnlTubular control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_pnlTubular As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SR_txtManufacturer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtManufacturer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtTypeOfPipe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtTypeOfPipe As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtPipeWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtPipeWeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtPipeOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtPipeOD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtThreadConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtThreadConnection As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtPipeGrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtPipeGrade As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtRange As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtTotalInspected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtTotalInspected As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtTotalAccepted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtTotalAccepted As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_pnlNotTubular control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_pnlNotTubular As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SR_txtMaterialDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtMaterialDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_txtResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_txtResult As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SR_grdServiceReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SR_grdServiceReport As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlMPIReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMPIReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''MPI_ddlMPIType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_ddlMPIType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''MPI_txtMPIHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtMPIHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_btnReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_btnReportNo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MPI_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''MPI_txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtSerialNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_calExpiredDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_calExpiredDate As Global.Raven.Web.Calendar

        '''<summary>
        '''MPI_txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_chkACIsASME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkACIsASME As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkACIsAPISpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkACIsAPISpec As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsACDS1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsACDS1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsACOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsACOther As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_txtACOtherDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtACOtherDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtQty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtDimension control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtDimension As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtAreaInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtAreaInspection As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtMaterial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtMaterial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtApplication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtApplication As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtSurfaceCondition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtSurfaceCondition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtContrast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtContrast As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtMetalSurfaceTemp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtMetalSurfaceTemp As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtMagneticParticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtMagneticParticle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtMaterialThickness control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtMaterialThickness As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtCleaner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtCleaner As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtSetCalibration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtSetCalibration As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtPenetrant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtPenetrant As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtPoleSpacing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtPoleSpacing As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtDeveloper control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtDeveloper As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_rbtnlYoke control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_rbtnlYoke As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''MPI_rbtnlCoil control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_rbtnlCoil As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''MPI_chkIsBlacklight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsBlacklight As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsRods control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsRods As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_rbtnlFluorescent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_rbtnlFluorescent As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''MPI_rbtnlContrastBW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_rbtnlContrastBW As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''MPI_chkIsDyePenetrant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsDyePenetrant As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsWireBrush control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsWireBrush As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsBlastCleaning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsBlastCleaning As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsGrinding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsGrinding As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_chkIsMachining control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_chkIsMachining As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''MPI_txtInspectionResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtInspectionResult As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_pnlMPIDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_pnlMPIDt As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''MPI_fuImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_fuImage As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''MPI_ddlPicGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_ddlPicGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''MPI_txtPicDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_txtPicDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MPI_btnUploadImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_btnUploadImage As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MPI_ImagePreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPI_ImagePreview As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''pnlHardnessTestReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHardnessTestReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HT_txtHardnessTestHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHardnessTestHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_btnReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_btnReportNo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''HT_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''HT_txtHardnessTestDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHardnessTestDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtPipeNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtPipeNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_ddlLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_ddlLocation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''HT_txtHRB1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHRB1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHRB2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHRB2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHRB3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHRB3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHRB4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHRB4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHRBAvg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHRBAvg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHB1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHB1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHB2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHB2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHB3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHB3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHB4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHB4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_txtHBAvg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_txtHBAvg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HT_grdHardnessTestDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HT_grdHardnessTestDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlDrillPipeInspectionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDrillPipeInspectionReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''DP_txtDrillPipeReportHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtDrillPipeReportHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_btnSearchDrillPipeReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_btnSearchDrillPipeReport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DP_txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''DP_txtSpecificationID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSpecificationID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtSpecificationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSpecificationCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_btnSearchSpecification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_btnSearchSpecification As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DP_txtSpecificationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSpecificationName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtWeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtGrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtGrade As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtConnection As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtRange As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtNominalWT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtNominalWT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Premium_txtMinOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Premium_txtMinOD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Premium_txtMaxID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Premium_txtMaxID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Premium_txtMinWall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Premium_txtMinWall As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Premium_txtMinShoulder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Premium_txtMinShoulder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Premium_txtMinSeal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Premium_txtMinSeal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinOD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinOD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMaxID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMaxID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinWall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinWall As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinShoulder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinShoulder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinSeal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinSeal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinTongSpacePB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinTongSpacePB As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMaxQC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMaxQC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtBevelDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtBevelDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMinQCDepth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMinQCDepth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMaxLengthPin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMaxLengthPin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_Class2_txtMaxPinNeck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_Class2_txtMaxPinNeck As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtDrillPipeReportDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtDrillPipeReportDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtSerialNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdBodyWear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdBodyWear As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdBent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdBent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdBodyDamage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdBodyDamage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdEMI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdEMI As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdUTEndArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdUTEndArea As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdPlasticCoating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdPlasticCoating As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdWall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdWall As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdWallRemanent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdWallRemanent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbdTubeClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbdTubeClass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcToolJointYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcToolJointYear As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcOutsideDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcOutsideDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcInsideDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcInsideDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcTongSpace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcTongSpace As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcThreadLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcThreadLength As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcBevelDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcBevelDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcLead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcLead As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcShoulderWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcShoulderWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcNeckLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcNeckLength As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcReface control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcReface As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtpcFinalCondition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtpcFinalCondition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcOutsideDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcOutsideDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcTongSpace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcTongSpace As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcQCDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcQCDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcQCDepth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcQCDepth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcShoulderWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcShoulderWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcBevelDia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcBevelDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcSealWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcSealWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcReface control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcReface As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtbcFinalCondition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtbcFinalCondition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DP_grdDrillPipeReportDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DP_grdDrillPipeReportDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlThroughVisualInspectionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlThroughVisualInspectionReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlInspectionTallyReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInspectionTallyReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlUTSpotCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUTSpotCheck As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UTSC_txtUTSpotCheckHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtUTSpotCheckHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_btnReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_btnReportNo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UTSC_calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_calReportDate As Global.Raven.Web.Calendar

        '''<summary>
        '''UTSC_txtNominalWT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtNominalWT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtMinimalWT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtMinimalWT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtUTSpotCheckDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtUTSpotCheckDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtTallyNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtTallyNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtWallThicknessInch1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtWallThicknessInch1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtWallThicknessInch2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtWallThicknessInch2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtWallThicknessInch3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtWallThicknessInch3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_txtRemark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_txtRemark As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UTSC_grdUTSpotCheckDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UTSC_grdUTSpotCheckDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlRotaryShoulderConnectionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRotaryShoulderConnectionReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlUTSpotEndArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUTSpotEndArea As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlCertificateInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCertificateInspection As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''COI_txtCertificateInspectionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtCertificateInspectionID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtCertificateNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtCertificateNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_calCertificateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_calCertificateDate As Global.Raven.Web.Calendar

        '''<summary>
        '''COI_txtOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtOwner As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtSerialNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtMaxGossWeightR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtMaxGossWeightR As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtLoadTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtLoadTest As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtDuration As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtSpecification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtSpecification As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtExamination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtExamination As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_txtResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtResult As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_caInspectionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_caInspectionDate As Global.Raven.Web.Calendar

        '''<summary>
        '''COI_calExpiredDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_calExpiredDate As Global.Raven.Web.Calendar

        '''<summary>
        '''COI_txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''COI_grdCertificateInspection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents COI_grdCertificateInspection As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.Raven.Web.copyRight
    End Class
End Namespace
