'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure

    Partial Public Class ReportImage

        '''<summary>
        '''frmReportImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmReportImage As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportTypeID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTypeID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportHdID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtReportImageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportImageID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ImageFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageFile As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''txtPicDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPicDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkShowOnMainReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowOnMainReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnUploadImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUploadImage As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''repImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repImages As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
