'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure

    Partial Public Class User

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.Raven.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.Raven.CSSToolbar

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtUserID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvUserName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtSalutation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSalutation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPersonID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPersonID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcademicTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcademicTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlSex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSex As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGender As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostalCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlReligion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReligion As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMobile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMobile As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlNationality control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNationality As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProfile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnUserProfileAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserProfileAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserProfileAddAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserProfileAddAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserProfileRemoveAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserProfileRemoveAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserProfileRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserProfileRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdUserProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUserProfile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdSite As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnUserSiteAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserSiteAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserSiteAddAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserSiteAddAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserSiteRemoveAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserSiteRemoveAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserSiteRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserSiteRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdUserSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUserSite As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCustomer As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnUserCustomerAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserCustomerAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserCustomerAddAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserCustomerAddAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserCustomerRemoveAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserCustomerRemoveAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUserCustomerRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUserCustomerRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdUserCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUserCustomer As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUser As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.Raven.Web.copyRight
    End Class
End Namespace
